audit_header: false
title: Financial Video Blog with Paul Medaglia
description: Our mission at -- CLIENT BRAND -- is to be your best resource for -- MARKET -- finance advice. Our team of professionals can answer any questions you might have. You can get all the information and the latest updates to learn how Cottman Executive Search can connect you with the right people.
show_custom_links: true
custom_links:
  - title: About
    url: /about/
  - title: Team
    url: /team/
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Paul Medaglia<br>Executive Recruiter & Advisor
  title:
  license_number:
  about_markdown: |
        Based in Greenwich, CT with offices in New York and London, Cottman Executive Search is a retained executive search firm specializing in senior management recruitment for clients in financial services, private equity and consulting firms worldwide. The firm was launched by Cindy Cottman in 2008, an executive search consultant serving the financial services industry since 1989 where she started her career with Korn Ferry and ran the practice for the firm in Europe before coming to the US to run the Risk, Compliance and Regulatory Group.
  brand: Cottman Executive Search
  brokerage:
  market:
  address: New York
  phone: 646-813-0603
  phone_type: Office
  phone2: 516-503-8325
  phone2_type: Mobile
  email: pmedaglia@ccexs.com
  url: http://cottmanexecutivesearch.com

CTAs:
  first_CTA_text: Schedule a Consultation
  first_CTA_URL: /contact/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "We would love to hear from you!"
    CTA_text: "We can help you today."
    CTA_link_text: "Contact Us"
    CTA_url: /contact/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: false
  facebook_url:
  linkedin_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with Paul Medaglia'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Paul Medaglia'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: Linking People with Opportunity
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#336699'
  theme_color: '#818181'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#336699'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
